version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: cfcoin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cfcoin
      MYSQL_USER: pia
      MYSQL_PASSWORD: panqueca
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
