version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: cfcoin
    restart: always
    environment:
      POSTGRES_USER: pia
      POSTGRES_PASSWORD: panqueca
      POSTGRES_DB: cfcoin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
